### ISSUE TITLE
Missing "./decorators/custom-element" export in "lit" package

### ISSUE THREAD

**Issue by jerrynim** [lit/lit#2206]
I upgraded lit@2.0.0-rc.2 to 2.0.0
and this error showed up

```
[vite:resolve] Missing "./decorators/custom-element" export in "lit" package
error during build:
Error: Missing "./decorators/custom-element" export in "lit" package
    at bail (/Users/jerrynim-zigbang/Desktop/lit-blog/.yarn/cache/vite-npm-2.4.4-dac9e9402c-075deeb5f9.zip/node_modules/vite/dist/node/chunks/dep-c1a9de64.js:38264:8)
    at resolve$1 (/Users/jerrynim-zigbang/Desktop/lit-blog/.yarn/cache/vite-npm-2.4.4-dac9e9402c-075deeb5f9.zip/node_modules/vite/dist/node/chunks/dep-c1a9de64.js:38340:10)
    at resolveExports (/Users/jerrynim-zigbang/Desktop/lit-blog/.yarn/cache/vite-npm-2.4.4-dac9e9402c-075deeb5f9.zip/node_modules/vite/dist/node/chunks/dep-c1a9de64.js:38769:12)
    at resolveDeepImport (/Users/jerrynim-zigbang/Desktop/lit-blog/.yarn/cache/vite-npm-2.4.4-dac9e9402c-075deeb5f9.zip/node_modules/vite/dist/node/chunks/dep-c1a9de64.js:38786:26)
    at tryNodeResolve (/Users/jerrynim-zigbang/Desktop/lit-blog/.yarn/cache/vite-npm-2.4.4-dac9e9402c-075deeb5f9.zip/node_modules/vite/dist/node/chunks/dep-c1a9de64.js:38575:11)
    at Object.resolveId (/Users/jerrynim-zigbang/Desktop/lit-blog/.yarn/cache/vite-npm-2.4.4-dac9e9402c-075deeb5f9.zip/node_modules/vite/dist/node/chunks/dep-c1a9de64.js:38459:28)
    at /Users/jerrynim-zigbang/Desktop/lit-blog/.yarn/cache/rollup-npm-2.55.1-800ab6ca2c-504f293723.zip/node_modules/rollup/dist/shared/rollup.js:20197:25
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

I'm using yarn2 Berry, lit, vite

**Comment by thescientist13** [comment]
Not sure if Vite has updated [their starter templates](https://github.com/vitejs/vite/tree/main/packages/create-vite), but they do support one for [Lit](https://github.com/vitejs/vite/tree/main/packages/create-vite/template-lit) so maybe worth comparing against that, or otherwise provide some code (ideally a sample repo) so that everyone can see what is happening.

Probably worth reviewing the discussion in #2198 though as I think if you can provide a reproduction repo and / or coordinate with the Vite team first, it could help uncover the root cause to determine if it is a Vite issue, or Lit issue.

If it is indeed an issue with how Lit is managing export maps or something similar on the npm / package.json side, having an example with something actionable for the Lit team to review will probably yield the best outcomes here in the Lit issue tracker.  (IMO)

**Comment by justinfagnani** [comment]
You need to import `'lit/decorators/custom-element.js'`

**Comment by jerrynim** [comment]
thanks @justinfagnani 
this occured when i use 'lit/decorators/custom-element' 
so, i change it
'lit/decorators/custom-element' => 'lit/decorators/custom-element.js'
'lit/decorators/property' => 'lit/decorators/property.js'
'lit/directives/style-map' => 'lit/directives/style-map.js'

**Comment by bobikel** [comment]
it works nice

**Comment by quocthanh2694** [comment]
> You need to import `'lit/decorators/custom-element.js'`

It works like a charm. Thanks a lot
