### ISSUE TITLE
TypeError: 'set' on proxy: trap returned falsish for property 'disabled' with React Testing Library

### ISSUE THREAD

**Issue by ashleyryan** [lit/lit#2281]
# Description

We are using VMware's Clarity react lib, @cds/react,  in our application, which is built on top of lit. When unit testing with React Testing Library (the [recommend test framework for React](https://reactjs.org/docs/testing.html)) we get the following error when attempting to use `await screen.findByLabel` on their Select component:

```
  TypeError: 'set' on proxy: trap returned falsish for property 'disabled'

      at node_modules/src/internal/utils/lit-element.ts:42:20
          at Array.forEach (<anonymous>)
      at syncProps (node_modules/src/internal/utils/lit-element.ts:42:6)
      at HTMLElement.updated (node_modules/src/forms/control/control.element.ts:291:5)
      at HTMLElement.performUpdate (node_modules/lit-element/src/lib/updating-element.ts:792:12)
      at node_modules/lit-element/src/lib/updating-element.ts:725:25
      at asyncGeneratorStep (node_modules/lit-element/lib/updating-element.js:8:103)
      at _next (node_modules/lit-element/lib/updating-element.js:10:194)
```

 We [reported the issue to the Clarity team](https://github.com/vmware/clarity/issues/5985), but they said it sounds like a lir or @lit-labs/react issue.
 
 Unfortunately I don't have a direct repro that doesn't go through Clarity, but their implementations are here:
 https://github.com/vmware/clarity/blob/next/packages/core/src/select/select.element.ts
 https://github.com/vmware/clarity/blob/next/packages/react/src/select/index.tsx

# Steps to Reproduce

We have create a barebones repository where the issue is explained in the readme and can be reproduced by running `yarn test` here: https://github.com/dturcotte/cds-select-test

## Expected Results

The error isn't returned and the test passes. @lit-labs/react should work with React Testing Library

**Comment by ashleyryan** [comment]
Nevermind, this is clearly an issue coming from Clarity's lit utils and how testing-library integrates with it: https://github.com/vmware/clarity/blob/a80cfc54f41b4e104d13baf9ee7a2d8c10e95820/packages/core/src/internal/utils/lit.ts
