### ISSUE TITLE
[labs/ssr] ModuleLoader linker fails with multiple concurrent entrypoints

### ISSUE THREAD

**Issue by aomarks** [lit/lit#2549]
Given two modules that both import `lit`, this approach works fine:

```ts
new ModuleLoader(...);
for (const mod of modules) {
  await loader.importModule(module, referrer);
}
```

But this approach consistently fails:

```ts
new ModuleLoader(...);
await Promise.all(modules.map((module) =>
  loader.importModule(module, referrer));
);
```

with an error like:

```
Error: request for '@lit/reactive-element' is not yet fulfilled
        at SourceTextModule.link (node:internal/vm/module:198:17)
        at ModuleLoader.importModule (/home/aomarks/work/wireit-lit/packages/labs/ssr/src/lib/module-loader.ts:107:7)
        at async Promise.all (index 1)
        at AsyncEventEmitter.<anonymous> (/home/aomarks/work/wireit-lit/packages/labs/eleventy-plugin-lit/src/index.ts:85:7)
        at async Promise.all (index 0)
        at async Eleventy.executeBuild (/home/aomarks/work/wireit-lit/packages/labs/eleventy-plugin-lit/node_modules/@11ty/eleventy/src/Eleventy.js:971:7)
```

Decent chance there is a timing issue in the `ModuleLoader` class https://github.com/lit/lit/blob/908f451d1444955571206588646efd04457d8d02/packages/labs/ssr/src/lib/module-loader.ts#L68

**Comment by aomarks** [comment]
cc @justinfagnani I spent a while poking around at `ModuleLoader`, but couldn't identify the problem here. I'll dig into this more deeply probably tomorrow, but just pinging in case this seems familiar to you, or something comes to mind.

**Comment by aomarks** [comment]
cc @justinfagnani @kevinpschaaf I spent a while poking around at `ModuleLoader`, but couldn't identify the problem here yet. I'll dig into this more deeply probably tomorrow, but just pinging in case this seems familiar to you, or something comes to mind.
