### ISSUE TITLE
[ssr] undefined attributes throw for lit elements

### ISSUE THREAD

**Issue by daKmoR** [lit/lit#2572]
# Description

Trying to ssr an undefined value/attribute of a LitElement throws.

# Steps to Reproduce

1. Write this code

```ts
import { render } from "@lit-labs/ssr/lib/render-with-global-dom-shim.js";
import { html, LitElement } from 'lit';

class MyEl extends LitElement {
  static get properties() {
    return {
      message: { type: String }
    }
  }
}

customElements.define('my-el', MyEl);

const template = ({ message }) => html`
  <p>${message}</p>
  <my-el message=${message}></my-el>
`;

const ssrResult = render(template({ message: undefined }));
//                                  👆 using `message: 'foo'` works as expected only undefined throws
let ssrStr = '';
for (const ssrPart of ssrResult) {
  ssrStr += await ssrPart;
}
console.log(ssrStr);
```

2. execute `node file.js`

## Expected Results

no error thrown

## Actual Results

```
file:///Users/html/test-ssr/node_modules/@lit-labs/ssr/lib/util/escape-html.js:19
export const escapeHtml = (str) => str.replace(/[&<>"']/g, (char) => replacements[char]);
                                       ^

TypeError: Cannot read properties of undefined (reading 'replace')
    at escapeHtml (file:///Users/html/test-ssr/node_modules/@lit-labs/ssr/lib/util/escape-html.js:19:40)
    at LitElementRenderer.renderAttributes (file:///Users/html/test-ssr/node_modules/@lit-labs/ssr/lib/element-renderer.js:88:40)
    at renderAttributes.next (<anonymous>)
    at renderTemplateResult (file:///Users/html/test-ssr/node_modules/@lit-labs/ssr/lib/render-lit-html.js:467:33)
    at renderTemplateResult.next (<anonymous>)
    at renderValue (file:///Users/html/test-ssr/node_modules/@lit-labs/ssr/lib/render-lit-html.js:354:16)
    at renderValue.next (<anonymous>)
    at render (file:///Users/html/test-ssr/node_modules/@lit-labs/ssr/lib/render-lit-html.js:336:12)
    at render.next (<anonymous>)
    at file:///Users/html/test-ssr/undefined.js:21:12
```

## Suggested changed

in here https://github.com/lit/lit/blob/main/packages/labs/ssr/src/lib/element-renderer.ts#L146

```diff
    *renderAttributes() {
        if (this.element !== undefined) {
            const { attributes } = this.element;
            for (let i = 0, name, value; i < attributes.length && ({ name, value } = attributes[i]); i++) {
                if (value === '') {
                    yield ` ${name}`;
                }
-                else {
+                else if (typeof value === 'string') {
                    yield ` ${name}="${escapeHtml(value)}"`;
                }
            }
        }
    }
```

## How can I best help?

would it help to prepare a PR?

**Comment by aomarks** [comment]
I think we should match the behavior of Lit on the browser. Looks like Lit will produce `<el attr>` when the attr value is null or undefined. So probably updating the `if (value === '')` line is the more correct solution.

A PR with a test for null and undefined cases would be great, if you're up for that!

**Comment by justinfagnani** [comment]
Hopefully the existing test infrastructure will ensure that server and client rendering are the same.

**Comment by daKmoR** [comment]
opened a pull request - tests are green.

not really sure if the "test infrastructure will ensure that server and client rendering are the same" 🤔

**Comment by daKmoR** [comment]
FYI: this has been released via `@lit-labs/ssr@2.0.4`
