### ISSUE TITLE
[lit-starter-ts] jest for testing instead of karma?

### ISSUE THREAD

**Issue by michaelwarren1106** [lit/lit#2616]
is that even possible?

I've tried all manner of configs to try to get jest up and running in a Typescript project using LitElement. But no matter what i've tried nothing has worked. Can you guys maybe include a sample project that uses Lit, Typescript and is tested with Jest?

**Comment by hungtcs** [comment]
+1

```
 FAIL  src/app/hello.element.spec.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Volumes/T7_Shield_APFS/Workspaces/@hungtcs/lit-starter/node_modules/lit/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import"@lit/reactive-element";import"lit-html";export*from"lit-element/lit-element.js";
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

    > 1 | import { LitElement, html } from 'lit';
        | ^
      2 | import { customElement, property } from 'lit/decorators.js';
      3 |
      4 | @customElement('lit-hello')

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1796:14)
      at Object.<anonymous> (src/app/hello.element.ts:1:1)

----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |                   
----------|---------|----------|---------|---------|-------------------
Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.225 s
Ran all test suites.
```

**Comment by michaelwarren1106** [comment]
this is a super old issue and i’ve used lit a ton more than i had back then. for anyone in 2022, id recommend not using jest and using @web/test-runner instead

**Comment by hungtcs** [comment]
@michaelwarren1106 I will try the official recommended @web/test-runner, use jest for testing is out of inertia.

**Comment by justinfagnani** [comment]
We definitely don't want to encourage testing in Jest because it's not a browser that any users use. We don't use Karma, but have updated starter kits to use `@web/test-runner`.
