### ISSUE TITLE
[labs/router] Nested routes not working

### ISSUE THREAD

**Issue by emilbonnek** [lit/lit#3209]
### Which package(s) are affected?

Other/unknown (please mention in description)

### Description

When I try to set up nested routing as described in [here](https://github.com/lit/lit/tree/main/packages/labs/router#nested-routes) I am getting an error `No route found for /<PARENT-ROUTE>/<CHILD-ROUTE>` when I refresh the page on the new route.

I tried debugging the code and I wasn't able to find out what causes the issue.
It seems that the [`_getRoute()` function](https://github.com/lit/lit/blob/42b1ae81ceaf8af1b740b818d6c85d302fff44b4/packages/labs/router/src/routes.ts#L229) is being called three times.

1.  The full route ("/<PARENT-ROUTE>/<CHILD-ROUTE>") is being checked against the parent components RouteConfig.
2.  The child route ("<CHILD-ROUTE>") is being checked against the child components RouteConfig.
3.  The full route ("/<PARENT-ROUTE>/<CHILD-ROUTE>") is being checked against the child components RouteConfig.

The last one is what is causing the error. When it isn't able to match a route it returns undefined and then it throws in `goto()`.

### Reproduction

Follow [this example ](https://github.com/lit/lit/tree/main/packages/labs/router#nested-routes).

I did a this:
```
export class MyApp extends LitElement {
  private _router = new Router(this, [
    { path: "/", render: () => html`<h1>Home</h1>` },
    { path: "/welcome/*", render: () => html`<my-welcome />` },
  ]);
  render() {
    return html`${this._router.outlet()}`;
  }
}
```

```
export class MyWelcome extends LitElement {
  private _router = new Router(this, [
    { path: "sign-in", render: () => html`<h2>Sign-in</h2>` },
    { path: "sign-up", render: () => html`<h2>Sign-up</h2>` },
    { path: "forgot-password", render: () => html`<h2>Forgot-password</h2>` },
  ]);
  render() {
    return html`${this._router.outlet()}`;
  }
```

And hit the `/welcome/sign-in` endpoint.

I used the vite starter template, but I don't think that should make a difference.

### Workaround

I have not found a workaround.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

Failing in @lit-labs/router 0.1.1

### Browser/OS/Node environment

Browser: Chrome 104.0.5112.81
OS: Windows 11
Node: v16.13.0

**Comment by zandaqo** [comment]
```js
    { path: "/welcome/*", render: () => html`<my-welcome />` },
```
Not sure about the router, but custom elements cannot be self-closing, try `<my-welcome></my-welcome>` instead.

**Comment by emilbonnek** [comment]
Yup, you are correct about the element needing to be self-closing. Didn't actually know that was required.
However it doesn't solve the issue with the router.

[I made a repo](https://github.com/emilbonnek/vite-lit-ts-router-project) to replicate the issue. The page is rendered correctly, but I get this error in console:
```
routes.ts:179 Uncaught (in promise) Error: No route found for /welcome/sign-in
    at Router.goto (routes.ts:179:15)
    at Router.hostConnected (router.ts:28:10)
    at reactive-element.ts:1036:55
    at Array.forEach (<anonymous>)
    at MyWelcome.connectedCallback (reactive-element.ts:1036:25)
    at MyWelcome.connectedCallback (lit-element.ts:189:11)
    at ChildPart._insert (lit-html.ts:1483:53)
    at ChildPart._commitNode (lit-html.ts:1523:36)
    at ChildPart._commitTemplateResult (lit-html.ts:1629:12)
    at ChildPart._$setValue (lit-html.ts:1456:12)
```

**Comment by AndrewJakubowicz** [comment]
Thank you for the repro. The issue is that you have nested multiple `Routers`, instead of `Routes`.

Using your repro, the issue is resolved when the Router in `my-welcome` is replaced with a `Routes` class.
E.g. `new Routes(this, [...` and importing `Routes` from `'@lit-labs/router/routes.js'`.

Action item: The case of accidentally nesting multiple `Routers` should raise a helpful error that only the top level element should use a `Router`, and nested elements should all use `Routes`.

**Comment by emilbonnek** [comment]
Aha that makes sense.  I thought I was being very thorough and had ruled out silly mistakes like that, but apparently not.
Thanks for looking at it and apologies for the alarming title!
