### ISSUE TITLE
[@lit-labs/analyzer] Cannot generate react wrapper with vite bundler

### ISSUE THREAD

**Issue by Cybertron01Z** [lit/lit#3334]
### Which package(s) are affected?

Other/unknown (please mention in description)

### Description

When I try to run `npx lit labs gen --react --out ../WebComponentsReact` the analyzer fails because I use vite as a bundler.

Since I use vite I set `"emitDeclarationOnly": true,` in the tsconfig.json.

The error
```
file:///...../node_modules/@lit-labs/analyzer/lib/javascript/modules.js:24
        throw new Error(`Could not determine output filename for '${sourcePath}'`);
              ^

Error: Could not determine output filename for 'src/index.ts'
    at getModule (file:///.../node_modules/@lit-labs/analyzer/lib/javascript/modules.js:24:15)
    at file:///..../node_modules/@lit-labs/analyzer/lib/analyzer.js:59:54
    at Array.map (<anonymous>)
    at Analyzer.analyzePackage (file:///...../node_modules/@lit-labs/analyzer/lib/analyzer.js:59:36)
    at Module.run (file:///...../node_modules/@lit-labs/cli/lib/generate/generate.js:33:35)
    at Object.run (file:///...../node_modules/@lit-labs/cli/lib/commands/labs.js:36:31)
    at async file:///...../node_modules/@lit-labs/cli/bin/lit.js:24:16
```

### Reproduction

I use following vite config
```ts
import { defineConfig } from 'vitest/config';
import { resolve, parse } from 'path';
import { globbySync } from 'globby';

const getComponents = () => {
  const components = globbySync('./src/**/!(*.(stories|test)).ts');
  return components.reduce((obj, path) => {
    return { ...obj, [parse(path).name]: resolve(__dirname, path) };
  }, {});
};

export default defineConfig({
  build: {
    outDir: 'dist',
    sourcemap: true,
    // @ts-ignore
    lib: {
      fileName: '[name]',
      formats: ['es'],
    },
    rollupOptions: {
      input: {
        ...getComponents(),
      },
      external: /^lit/,
    },
  },
  test: {
    environment: 'jsdom',
  },
});
```

tsconfig
```json
{
  "compilerOptions": {
    "module": "ESNext",
    "lib": [
      "ES2020",
      "DOM",
      "DOM.Iterable"
    ],
    "declaration": true,
    "emitDeclarationOnly": true,
    "outDir": "./types",
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "noFallthroughCasesInSwitch": true,
    "moduleResolution": "Node",
    "isolatedModules": true,
    "allowSyntheticDefaultImports": true,
    "experimentalDecorators": true,
    "forceConsistentCasingInFileNames": true,
    "useDefineForClassFields": false,
    "skipLibCheck": true,
    "plugins": [
      {
        "name": "ts-lit-plugin"
      }
    ]
  },
  "include": [
    "src/**/*.ts",
    "vite.d.ts"
  ],
  "exclude": [
    "src/**/*.stories.ts",
    "src/**/*.test.ts"
  ],
  "references": [
    {
      "path": "./tsconfig.node.json"
    }
  ]
}
```

### Workaround

I wrote my own react wrapper gen script but it is quite slow :lau

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

0.1.0

### Browser/OS/Node environment

Node: v18.10.0

**Comment by loic-enedis** [comment]
I am having it too, any way to by pass this issue ?
