### ISSUE TITLE
[labs/virtualizer] Error when immediately re-rendering (before async connect code runs)

### ISSUE THREAD

**Issue by jpzwarte** [lit/lit#3481]
### Which package(s) are affected?

Virtualizer (@lit-labs/virtualizer)

### Description

When using the latest `0.0.0-masonry-preview-20221107225026` preview, the virtualizer throws an error on initial render. It still seems to work after that.

The error:
```
Virtualizer.js:168 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'detach')
    at Virtualizer.disconnected (Virtualizer.js:168:1)
    at VirtualizeDirective._makeVirtualizer (virtualize.js:74:1)
    at VirtualizeDirective._updateVirtualizerConfig (virtualize.js:59:1)
    at VirtualizeDirective.update (virtualize.js:48:1)
    at VirtualizeDirective._$resolve (directive.ts:134:1)
    at resolveDirective (lit-html.ts:1075:1)
    at ChildPart._$setValue (lit-html.ts:1353:1)
    at TemplateInstance._update (lit-html.ts:1181:1)
    at ChildPart._commitTemplateResult (lit-html.ts:1525:1)
    at ChildPart._$setValue (lit-html.ts:1375:1)
```

This is with the following markup:

```
        <tbody @visibilityChanged=${this.#onVisibilityChanged}>
          ${virtualize({ items: this.items, renderItem: item => this.renderItem(item) })}
        </tbody>
```

This does not throw any error with `0.7.2`

### Reproduction

-

### Workaround

-

### Is this a regression?

Yes. This used to work, but now it doesn't.

### Affected versions

Failing in 0.0.0-masonry-preview-20221107225026, used to work in 0.7.2

### Browser/OS/Node environment

-

**Comment by bicknellr** [comment]
Could you provide a demo? I'm having trouble reproducing this.

**Comment by jpzwarte** [comment]
@bicknellr https://kind-plant-088739303-104.westeurope.1.azurestaticapps.net/?path=/story/grid_grid--api (from https://github.com/sanomalearning/design-system/pull/104)

**Comment by graynorton** [comment]
@jpzwarte It looks like, for some reason, the `virtualize` directive is making an instance of its internal `Virtualizer` class and then immediately tearing it down and creating another. There's some async code that runs as part of the initial instance creation, so if something causes the instance to be torn down before this code runs, we can end up in a situation where things that the tear-down code assumes to exist don't actually exist yet.

We can of course just guard against the case where those things don't exist, but before we do that I'm curious to know what it is about your situation (could be in your `<sl-grid>` source or I suppose something in your Storybook setup) is causing `virtualize` to create and immediately replace its internal `Virtualizer` instance.

There is some relatively new code that tears down an instance and makes a new one when you change layouts, but in this case it looks like you're just using the default layout and not doing anything fancy—is that correct? Do you have any other ideas about what might be unusual in your setup?

Here's a Playground that tries to repro your issue but doesn't, in case that helps: https://lit.dev/playground/#gist=59972ad9a469f1bc0ecae56b49c068ff

**Comment by jpzwarte** [comment]
@graynorton Thanks for the explanation. As far as I know, I'm not doing anything fancy, but feel free to take a look yourself; the code is OSS: https://github.com/sanomalearning/design-system/blob/main/packages/grid/src/grid.ts

The only thing I can think of is that it changes the `@state() columns` variable in a `slotchange` handler. Perhaps that is causing virtualize to run a second time? But afaik that pattern is not that uncommon (it renders the columns in the `renderItem` callback of `virtualize`).

**Comment by jpzwarte** [comment]
@graynorton Right, when I add a guard that only renders the table when `this.columns.length` is truthy, the error disappears.

**Comment by graynorton** [comment]
Thanks, @jpzwarte!

Here's a reduced repro case: https://lit.dev/playground/#gist=f26038e7447c5788b90b2d3f4664c863
And the same with `0.7.2` (no error): https://lit.dev/playground/#gist=48a107d1b81128200030289c55d6714f

**Comment by cintaccs** [comment]
@graynorton I have the issue - I believe without any slots involved. It occurs whenever I re-visit page. I.e. if the virtualizer displays a list of item - and I click on an item (loading the page with the item content overwriting the virtualizer) then when I "go back" (in principle I delete the item content and refresh the original "parent" content) I get:

<img width="668" alt="Screenshot 2022-12-12 at 23 16 40" src="https://user-images.githubusercontent.com/4300051/207169450-a8afbd68-1a84-4bcc-a62c-628e34e47f1c.png">

I believe the list is correct - only the throwing of error - trying to detach something that is no longer there maybe - is the issue. I have the issue of initial empty pages on first render also - not sure whether that is related.

**Comment by graynorton** [comment]
@cintaccs Thanks for the report!

Any chance you can share more information about specifically how you're moving between views (i.e., replacing the virtualizer with the item content and then "refreshing" it when you "go back")?

The ideal would be a simple repro case in the Lit Playground, but just pasting relevant code snippets here or pointing me to a repository (or a running instance of your app) would also be helpful.

**Comment by cintaccs** [comment]
@graynorton :-) yea... I will have to think about how I can do that. It is a pretty huge stack/application nowadays... but I will try. It seems rather constant and generic across all the use-cases though. The "go back" basically changes the state at the parent and the reactive props are used to change the page content - so I am not specifically doing anything for the refresh apart from a rather complex factory of viewtypes etc.

**Comment by cintaccs** [comment]
@graynorton not sure whether you would be interested in that - but eventually it might be easier to show you directly in a zoom meeting or whatever you prefer. If you are interested in that - please write me on cs@cintac.com

**Comment by cintaccs** [comment]
@graynorton no layout specified - just itemsArr and renderfunc

**Comment by graynorton** [comment]
Reopening—see new symptom and detailed repro case in this Discord thread:

https://discord.com/channels/1012791295170859069/1062368232276775053

I think I know the rough shape of a proper fix, will confirm.

**Comment by cintaccs** [comment]
@graynorton I dont have discord at the moment - so I cant confirm whether it is also "my case" - however since the recommended fix with the 
```
 .layout=${flow()}
```
I haven't really seen problems. I have got the issue with the re-rendering - it appeared to be an unhandled real error in the application I think that stopped the request update somehow.

With the later builds - I have only seen a few "snap" crashes (1 or 2) ... which might be unrelated - but in the past could occur during virtualizer use.

By the way - when you have a longer list (so the scroll thumb is needed) and the list content updates (in the background for whatever reason - collapse expand logic e.g.) then the list will be OK - however the scroll track thumb will stay in position (like if the retain position function is kicking in where it shouldn't ... ) .. not sure whether that is an issue or me...  :-)

**Comment by justinfagnani** [comment]
Was this fixed by https://github.com/lit/lit/pull/3624?
