### ISSUE TITLE
keyed with cache directive causing `Uncaught (in promise) TypeError: partValue.pop is not a function`

### ISSUE THREAD

**Issue by kbfirebreather** [lit/lit#3637]
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

I have a scenario where I'm trying to cache something that is rendered based on a provided key. If the key changes, I want the cached object to be re-rendered. If the key is a certain value, I want to render something different. When going from rendering the cached object to rendering something different, an uncaught exception is logged in the console, causing unexpected behavior on the rendered page. 

The exception I see in the console:

```
Uncaught (in promise) TypeError: partValue.pop is not a function
    at CacheDirective.update (cache.js:27:41)
    at CacheDirective._$resolve (directive.js:42:21)
    at resolveDirective (lit-html.js:659:57)
    at resolveDirective (lit-html.js:659:17)
    at ChildPart._$setValue (lit-html.js:823:17)
    at TemplateInstance._update (lit-html.js:737:26)
    at ChildPart._commitTemplateResult (lit-html.js:984:35)
    at ChildPart._$setValue (lit-html.js:847:18)
    at render (lit-html.js:1459:10)
    at MyElement.update (lit-element.js:120:28)
```

### Reproduction

The text should change to `This is a bad key` but it doesn't.

https://lit.dev/playground/#sample=examples%2Fdirective-cache&project=W3sibmFtZSI6Im15LWVsZW1lbnQudHMiLCJjb250ZW50IjoiaW1wb3J0IHtMaXRFbGVtZW50LCBodG1sfSBmcm9tICdsaXQnO1xuaW1wb3J0IHtjdXN0b21FbGVtZW50LCBwcm9wZXJ0eX0gZnJvbSAnbGl0L2RlY29yYXRvcnMuanMnO1xuaW1wb3J0IHtjYWNoZX0gZnJvbSAnbGl0L2RpcmVjdGl2ZXMvY2FjaGUuanMnO1xuaW1wb3J0IHtrZXllZH0gZnJvbSAnbGl0L2RpcmVjdGl2ZXMva2V5ZWQuanMnO1xuXG5AY3VzdG9tRWxlbWVudCgnbXktZWxlbWVudCcpXG5leHBvcnQgY2xhc3MgTXlFbGVtZW50IGV4dGVuZHMgTGl0RWxlbWVudCB7XG4gIFxuICBAcHJvcGVydHkoe3R5cGU6IE51bWJlcn0pXG4gIGtleSA9IDE7XG5cbiAgcmVuZGVyKCkge1xuICAgIHJldHVybiBodG1sYFxuICAgICAgPGgzPmNhY2hlIGRpcmVjdGl2ZSBleGFtcGxlPC9oMz5cblxuICAgICAgPGJ1dHRvbiBAY2xpY2s9JHt0aGlzLnRvZ2dsZVZpZXd9PkluY3JlbWVudCBrZXk8L2J1dHRvbj48aHI-XG5cbiAgICAgICAgXG4gICAgICAke2tleWVkKHRoaXMua2V5LCBjYWNoZSh0aGlzLnJlbmRlclZpZXcoKSkpfVxuICAgIGA7XG4gIH1cbiAgXG4gIHJlbmRlclZpZXcoKSB7XG4gICAgaWYgKHRoaXMua2V5ID09PSAzKSB7XG4gICAgICAvKipcbiAgICAgIENhdXNlcyBcbiAgICAgIFVuY2F1Z2h0IChpbiBwcm9taXNlKSBUeXBlRXJyb3I6IHBhcnRWYWx1ZS5wb3AgaXMgbm90IGEgZnVuY3Rpb25cbiAgICAgICAgYXQgQ2FjaGVEaXJlY3RpdmUudXBkYXRlIChjYWNoZS5qczoyNzo0MSlcbiAgICAgICAgYXQgQ2FjaGVEaXJlY3RpdmUuXyRyZXNvbHZlIChkaXJlY3RpdmUuanM6NDI6MjEpXG4gICAgICAgIGF0IHJlc29sdmVEaXJlY3RpdmUgKGxpdC1odG1sLmpzOjY1OTo1NylcbiAgICAgICAgYXQgcmVzb2x2ZURpcmVjdGl2ZSAobGl0LWh0bWwuanM6NjU5OjE3KVxuICAgICAgICBhdCBDaGlsZFBhcnQuXyRzZXRWYWx1ZSAobGl0LWh0bWwuanM6ODIzOjE3KVxuICAgICAgICBhdCBUZW1wbGF0ZUluc3RhbmNlLl91cGRhdGUgKGxpdC1odG1sLmpzOjczNzoyNilcbiAgICAgICAgYXQgQ2hpbGRQYXJ0Ll9jb21taXRUZW1wbGF0ZVJlc3VsdCAobGl0LWh0bWwuanM6OTg0OjM1KVxuICAgICAgICBhdCBDaGlsZFBhcnQuXyRzZXRWYWx1ZSAobGl0LWh0bWwuanM6ODQ3OjE4KVxuICAgICAgICBhdCByZW5kZXIgKGxpdC1odG1sLmpzOjE0NTk6MTApXG4gICAgICAgIGF0IE15RWxlbWVudC51cGRhdGUgKGxpdC1lbGVtZW50LmpzOjEyMDoyOClcbiAgICAgICovXG4gICAgICByZXR1cm4gaHRtbGBUaGlzIGlzIGEgYmFkIGtleWA7IC8vIGNhdXNlcyBVbmNhdWdodCAoaW4gcHJvbWlzZSkgVHlwZUVycm9yOiBwYXJ0VmFsdWUucG9wIGlzIG5vdCBhIGZ1bmN0aW9uXG4gICAgfVxuICAgcmV0dXJuIGh0bWxgS2V5IFZhbHVlOiAke3RoaXMua2V5fWA7IFxuICB9XG5cbiAgcHJpdmF0ZSB0b2dnbGVWaWV3KCkge1xuICAgIHRoaXMua2V5Kys7XG4gIH1cbn1cbiJ9LHsibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPHN0eWxlPlxuICBib2R5IHsgZm9udC1mYW1pbHk6IHNhbnMtc2VyaWY7IH1cbjwvc3R5bGU-XG5cbjxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiIHNyYz1cIi4vbXktZWxlbWVudC5qc1wiPjwvc2NyaXB0PlxuXG48bXktZWxlbWVudD48L215LWVsZW1lbnQ-XG4ifSx7Im5hbWUiOiJwYWNrYWdlLmpzb24iLCJjb250ZW50Ijoie1xuICBcImRlcGVuZGVuY2llc1wiOiB7XG4gICAgXCJsaXRcIjogXCJeMi4wLjBcIixcbiAgICBcIkBsaXQvcmVhY3RpdmUtZWxlbWVudFwiOiBcIl4xLjAuMFwiLFxuICAgIFwibGl0LWVsZW1lbnRcIjogXCJeMy4wLjBcIixcbiAgICBcImxpdC1odG1sXCI6IFwiXjIuMC4wXCJcbiAgfVxufSIsImhpZGRlbiI6dHJ1ZX1d

### Workaround

I have not found a workaround.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

2.2.8

### Browser/OS/Node environment

Browser: Chrome: 109.0.5414.120 
OS: Windows 10
Node: v16.14.0
NPM: 8.3.1

**Comment by 43081j** [comment]
im gonna guess its because if you have a directive in a directive, the part is the overall outer part:

```ts
html`
  ${directiveA(directiveB('foo'))}
`;
```

would have one `Part`, a `ChildPart` which is the same one passed to both directives.

so this comment:

https://github.com/lit/lit/blob/e51ff229843aaac22805bc0a39bf5e6db6862a5c/packages/lit-html/src/directives/cache.ts#L50-L51

isn't true since the part could have already been through a parent directive at that point, resulting in it not being an array.

no clue how this'd be fixed but that seems to be why it errors for anyone who looks into this
