### ISSUE TITLE
Scoped styles in stylesheet throws error

### ISSUE THREAD

**Issue by emilbillberg** [lit/lit#3654]
### Which package(s) are affected?

SSR (@lit-labs/ssr)

### Description

When I add a variable to a scoped stylesheet in SSR:

```
render() {
    return html`
      <style>
        :host {
          color: ${this.name};
        }
      </style>
      <div>
        <h1>Hello, <span>${this.name}</span>!</h1>
        <p>Count: ${this.count}</p>
        <button @click=${() => this.count++}>++</button>
      </div>
    `;
  }
```

it throws an error:
```
Error: unexpected final partIndex: 3 !== 4
    at renderTemplateResult (file://file:///home/projects/lit-ssr-global-adqm9p/node_modules/@lit-labs/ssr/lib/render-value.js:518:15)
    at renderTemplateResult.next (<anonymous>)
    at Module.renderValue (file://file:///home/projects/lit-ssr-global-adqm9p/node_modules/@lit-labs/ssr/lib/render-value.js:351:16)
    at renderValue.next (<anonymous>)
    at LitElementRenderer.renderShadow (file://file:///home/projects/lit-ssr-global-adqm9p/node_modules/@lit-labs/ssr/lib/lit-element-renderer.js:68:33)
    at renderShadow.next (<anonymous>)
    at renderTemplateResult (file://file:///home/projects/lit-ssr-global-adqm9p/node_modules/@lit-labs/ssr/lib/render-value.js:503:25)
    at renderTemplateResult.next (<anonymous>)
    at Module.renderValue (file://file:///home/projects/lit-ssr-global-adqm9p/node_modules/@lit-labs/ssr/lib/render-value.js:351:16)
    at renderValue.next (<anonymous>)
```

### Reproduction

https://stackblitz.com/edit/lit-ssr-global-adqm9p

### Workaround

I have not found a workaround

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

3.0.1

### Browser/OS/Node environment

Chrome  version 109.0.5414.119

**Comment by eins78** [comment]
I have encountered the same problem, and made an alternative repro before I found this Github issue.
Its based on the SSR demo in the lit repo under `examples/nextjs` and might be of help, it's on stackblitz: https://stackblitz.com/edit/github-wqinjx-cyxj73?file=src%2Fsimple-greeter.ts%3AL48

A cursory look with the Debugger revealed that the JS values are not "filled in" to the Template Literal (as `lit-html` would do) when it reaches the `renderValue` function in `ssr/lb/render-value.js`.
