### ISSUE TITLE
custom element constructors must call super() first and must not return a different object

### ISSUE THREAD

**Issue by hmendes00** [lit/lit#3776]
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

"lit": "2.6.1"

When I try to define a Lit component dynamically it gives me the error in the title
`custom element constructors must call super() first and must not return a different object`

Dummy Component definition:
```html
@customElement('my-list-test')
export class MyListLit extends LitElement {
  @state() private selectedList: ReadonlyArray<MyList> = []

  @state()
  private activityDataList: ActivityDataList = {
    activities: [],
    hasNextPage: false,
    isReady: false,
    loadNextPage: () => {},
  }

  private readonly sectionTitle = 'section title'

  static styles = unsafeCSS(styles)
 }
```

main window
```
window.addEventListener('registerthis', e => {
      console.log('========== FOUND', e.detail.otherWindow)
      e.detail.otherWindow.customElements.define('my-list-test', MyListLit)
    })
```

child window
```
window.opener.dispatchEvent(new CustomEvent('registerthis', { detail: { otherWindow: currentChildWindow } }))
```

```
lit-html.ts:1122 Uncaught TypeError: custom element constructors must call super() first and must not return a different object
    at TemplateInstance._clone (lit-html.ts:1122:52)
    at ChildPart._commitTemplateResult (lit-html.ts:1528:33)
    at ChildPart._$setValue (lit-html.ts:1375:12)
    at TemplateInstance._update (lit-html.ts:1181:16)
    at ChildPart._commitTemplateResult (lit-html.ts:1538:16)
    at ChildPart._$setValue (lit-html.ts:1375:12)
    at render (lit-html.ts:2169:8)
    at AddToContactsLit.update (lit-element.ts:165:24)
    at AddToContactsLit.performUpdate (reactive-element.ts:1331:14)
```

Running with vite and yarn workspaces using "lit": "2.6.1"

(The Reproduction Code doesn't give the same error, but the component doesn't work either. It gets defined, but shadow dom doesn't work)

### Reproduction

https://lit.dev/playground/#project=W3sibmFtZSI6InJlcHJvLnRzIiwiY29udGVudCI6ImltcG9ydCB7aHRtbCwgY3NzLCBMaXRFbGVtZW50IH0gZnJvbSAnbGl0JztcbmltcG9ydCB7Y3VzdG9tRWxlbWVudCwgcHJvcGVydHksIHN0YXRlfSBmcm9tICdsaXQvZGVjb3JhdG9ycy5qcyc7XG5cblxuZXhwb3J0IGNsYXNzIE15TGlzdExpdCBleHRlbmRzIExpdEVsZW1lbnQge1xuICBzdGF0aWMgc3R5bGVzID0gY3NzYHAgeyBjb2xvcjogYmx1ZSB9YDtcblxuICBAcHJvcGVydHkoKVxuICBfbnVtQ2xpY2tzID0gMDtcbkBzdGF0ZSgpIGFzZCA9ICdzZHNkJ1xuXG4gIHJlbmRlcigpIHtcbiAgICByZXR1cm4gaHRtbGBcbiAgICAgIDxwPkNsaWNraW5nIHRoZSBidXR0b24gYmVsb3cgaXMgZXhwZWN0ZWQgdG8gdXBkYXRlIHRoZSB0ZXh0LCBidXQgaXQgZG9lc24ndDo8L3A-XG4gICAgICA8YnV0dG9uIEBjbGljaz0ke3RoaXMuX29uQ2xpY2tCdXR0b259PkNsaWNrIG1lPC9idXR0b24-XG4gICAgICA8cD5Zb3UgaGF2ZSBjbGlja2VkICR7dGhpcy5fbnVtQ2xpY2tzfSB0aW1lczwvcD5cbiAgICBgO1xuICB9XG4gIFxuICBfb25DbGlja0J1dHRvbigpIHtcbiAgfVxufVxuXG53aW5kb3cuYWRkRXZlbnRMaXN0ZW5lcigncmVnaXN0ZXJ0aGlzJywgZSA9PiB7XG5lLmRldGFpbC5vdGhlcldpbmRvdy5jdXN0b21FbGVtZW50cy5kZWZpbmUoJ215LWxpc3QtdGVzdCcsIE15TGlzdExpdClcbiAgICB9KVxuXG4ifSx7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhRE9DVFlQRSBodG1sPlxuPGhlYWQ-XG4gIDxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiIHNyYz1cIi4vcmVwcm8uanNcIj48L3NjcmlwdD5cbiA8c2NyaXB0PlxuXG5zZXRUaW1lb3V0KCgpID0-IHtcbndpbmRvdy5vcGVuKCdhYmMuaHRtbCcpXG59LCAxMDAwKVxuXG5cbjwvc2NyaXB0PlxuPC9oZWFkPlxuPGJvZHk-XG48L2JvZHk-XG4ifSx7Im5hbWUiOiJwYWNrYWdlLmpzb24iLCJjb250ZW50Ijoie1xuICBcImRlcGVuZGVuY2llc1wiOiB7XG4gICAgXCJsaXRcIjogXCJeMi4wLjBcIixcbiAgICBcIkBsaXQvcmVhY3RpdmUtZWxlbWVudFwiOiBcIl4xLjAuMFwiLFxuICAgIFwibGl0LWVsZW1lbnRcIjogXCJeMy4wLjBcIixcbiAgICBcImxpdC1odG1sXCI6IFwiXjIuMC4wXCJcbiAgfVxufSIsImhpZGRlbiI6dHJ1ZX0seyJuYW1lIjoiYWJjLmh0bWwiLCJjb250ZW50IjoiPCFET0NUWVBFIGh0bWw-XG48aGVhZD5cbiA8c2NyaXB0PlxuXG5zZXRUaW1lb3V0KCgpID0-IHtcbndpbmRvdy5vcGVuZXIuZGlzcGF0Y2hFdmVudChuZXcgQ3VzdG9tRXZlbnQoJ3JlZ2lzdGVydGhpcycsIHsgZGV0YWlsOiB7IG90aGVyV2luZG93OiB3aW5kb3cgfSB9KSlcbn0sIDEwMDAwKVxuXG5cbjwvc2NyaXB0PlxuPC9oZWFkPlxuPGJvZHk-XG4gIFxuPG15LWxpc3QtdGVzdD48L215LWxpc3QtdGVzdD5cbjwvYm9keT5cbiJ9XQ

### Workaround

I have not found a workaround

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

2.6.1

### Browser/OS/Node environment

Browser: Chrome  111.0.5563.146
OS: macOS  Ventura 13.2.1 
Node Version: 16.16.0
Npm version: 6.14.18

**Comment by justinfagnani** [comment]
Are you using a build step that compiles to ES5?
