### ISSUE TITLE
[@lit-labs/nextjs] TypeError: this._$Ek is not a function

### ISSUE THREAD

**Issue by raoufswe** [lit/lit#3845]
### Which package(s) are affected?

SSR (@lit-labs/ssr)

### Description

When `@lit-labs/nextjs` is added to a next@13 app that imports a lit component package in a yarn workspace monorepo, the server throws the following error. 

<img width="1280" alt="Screenshot 2023-04-26 at 17 45 48" src="https://user-images.githubusercontent.com/28605803/234630019-58eed2ce-ef63-4e8a-923d-9de0cfe37e73.png">

I suspect the issue might originate from a conflict of sub-dependencies as the app workspace sets [hoistingLimits](https://yarnpkg.com/configuration/manifest/#installConfig) to workspaces to hoist dependencies to the top level within the scope of the workspace. removing this config solves the issues but it isn't favorable in our case to avoid version conflicts between different packages in the monorepo.

extra details that might be useful for debugging: 
- the error is thrown from [this method](https://github.com/lit/lit/blob/main/packages/reactive-element/src/reactive-element.ts#L1472)
- the imported lit component is a button, and the bug persists with and without wrapping it with the React wrapper
- the lit component is tested in different client-side environments such as react, vue and anuglar and it works as expected, so I assume it's an SSR-related issue. 

### Reproduction

- the bug can be reproduced in [this branch ](https://github.com/justeattakeaway/pie/tree/pie-lit-next-ssr)
- the readme has some instructions to set up the repo but running `yarn` in the root and then cd-ing to `app/examples/wc-next13` and running `yarn dev` should be enough to reproduce the issue. 

### Workaround

removing  `installConfig` [here](https://github.com/justeattakeaway/pie/blob/pie-lit-next-ssr/apps/examples/wc-next13/package.json) or just moving `@lit-labs/nextjs` to the root package.json should get rid of the error. 

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

0.1.1

### Browser/OS/Node environment

Chrome
next@13

**Comment by raoufswe** [comment]
I'm a bit new to the codebase and still trying to figure my way out, but I believe the issue is somewhere in [these few lines](https://github.com/lit/lit/blob/main/packages/labs/nextjs/src/index.ts#L19) as commenting them seems to get rid of the error.

**Comment by augustjk** [comment]
@raoufswe Regarding update 3, the problem with doing that would be that you won't get the production version when you need it. I'm curious if `yarn build && yarn start` will work with that.

It does confirm that the problem is something is pulling the production (default) build when it's running in dev mode with `yarn dev`.

**Comment by raoufswe** [comment]
@augustjk yea that's definitely not ideal, it's just a finding that I came across and thought might help us find to the actual problem :'(

**Comment by augustjk** [comment]
I'm seeing this in a different project with npm. I'll have to investigate further. Something about the `next` cli running in dev mode is not bringing in the correct export from `@lit/reactive-element` depending on where it's being imported from.

I have found that running `NODE_OPTIONS=--conditions=development npm run dev` is a valid workaround for me. @raoufswe maybe `NODE_OPTIONS=--conditions=development yarn dev` might work for you?

Needs further investigation for this to work without this.

**Comment by hrmcdonald** [comment]
We've run into what appears to be a similar issue here with astro, vite, and pnpm.

```
Lit is in dev mode. Not recommended for production! See https://lit.dev/msg/dev-mode for more information.
Multiple versions of Lit loaded. Loading multiple versions is not recommended. See https://lit.dev/msg/multiple-versions for more information.
 error   r._$AT is not a function
  File:
    /<my-repo-path>/apps/docs/<my-repo-path>/node_modules/.pnpm/lit-html@2.7.3/node_modules/lit-html/node/lit-html.js:6:3039
  Stacktrace:
TypeError: r._$AT is not a function
    at N (file:///<my-repo-path>/node_modules/.pnpm/lit-html@2.7.3/node_modules/lit-html/node/lit-html.js:6:3039)
    at renderValue (file:///<my-repo-path>/node_modules/.pnpm/@lit-labs+ssr@3.1.2/node_modules/@lit-labs/ssr/lib/render-value.js:341:17)
    at renderValue.next (<anonymous>)
    at renderTemplateResult (file:///<my-repo-path>/node_modules/.pnpm/@lit-labs+ssr@3.1.2/node_modules/@lit-labs/ssr/lib/render-value.js:391:24)
    at renderTemplateResult.next (<anonymous>)
    at renderValue (file:///<my-repo-path>/node_modules/.pnpm/@lit-labs+ssr@3.1.2/node_modules/@lit-labs/ssr/lib/render-value.js:345:16)
    at renderValue.next (<anonymous>)
    at LitElementRenderer.renderShadow (file:///<my-repo-path>/node_modules/.pnpm/@lit-labs+ssr@3.1.2/node_modules/@lit-labs/ssr/lib/lit-element-renderer.js:69:16)
    at renderShadow.next (<anonymous>)
    at render (@astrojs/lit/server.js:79:3)
    at render.next (<anonymous>)
    at Object.renderToStaticMarkup (@astrojs/lit/server.js:108:11)
    at renderFrameworkComponent (/<my-repo-path>/node_modules/.pnpm/astro@2.4.3_@types+node@18.0.0_less@4.1.3_sass@1.52.3/node_modules/astro/dist/runtime/server/render/component.js:178:66)
```

The `NODE_OPTIONS=--conditions=development` workaround fixes this issue for us for now.

**Comment by raoufswe** [comment]
I did a bit more digging into this and found out that when a nextjs app is not hosted in a monorepo, the server won't throw even if you don't add the `--conditions=development` flag. However, as shown in my recording, the app is referencing production builds unless you explicitly add the flag 👀 

https://github.com/lit/lit/assets/28605803/bbe808ed-96ab-4cea-a462-d42c73c83d6f
