### ISSUE TITLE
[@lit-labs/nextjs] - Can't run nextjs example on Windows machine

### ISSUE THREAD

**Issue by aneta-kjeldsen** [lit/lit#3859]
### Which package(s) are affected?

SSR (@lit-labs/ssr)

### Description

I've tried to download locally following example: https://stackblitz.com/edit/nextjs-lit-ssr and run it on my Windows machine, but i'm getting following exception: 
```
error - ReferenceError: Cannot access 'Fragment' before initialization
    at Module.Fragment (webpack-internal:///./node_modules/@lit-labs/ssr-react/node/jsx-dev-runtime.js:4:57)
    at eval (webpack-internal:///./node_modules/@lit-labs/ssr-react/node/jsx-dev-runtime.js:27:69) {
  page: '/'
}
```

### Reproduction

Go to: https://stackblitz.com/edit/nextjs-lit-ssr?file=README.md

1. download the example on Windows machine
2. run `npm i && npm run dev`

### Workaround

No workarounds for this. However, when we run example in MacOS using the same version of Node - all seems to be working fine.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

Failing: 0.1.1

### Browser/OS/Node environment

OS: Windows 10 
Browser: Chrome Version 112.0.5615.138
Node: v16.14.2
Npm: 8.5.0

**Comment by augustjk** [comment]
I am able to reproduce this. Unfortunately it seems webpack has no consistency in what order it bundles things. In MacOS, the `react` package shows up first in the bundle so it's fine, but in Windows `@lit-labs/ssr-react` shows up first before `react` so `Fragment` isn't available then.

It might potentially be due to some circular reference (which is totally fine with ES modules) https://github.com/webpack/webpack/issues/12724 but nothing obvious is standing out as circular in the the `@lit-labs/ssr-react` code itself.

This requires more investigation, but honestly I'm not sure about priority of this. We don't want to ignore Windows users, but personally I've resorted to using WSL for development. (This does seem to work on WSL2 Ubuntu).

**Comment by aneta-kjeldsen** [comment]
Please feel free to close the issue as you fit, as it's not relevant to Lit libraries. Thanks for helping out and pointing us in the right direction.

**Comment by tigrr** [comment]
I don't think the issue should be closed. No matter the causes, the problem is still there, and there is no workaround.
I can't test `@lit-labs/nextjs` package and verify that it works because of this. When I try to set up my own test Next project with the library, it doesn't seem to produce expected html on the server.

**Comment by ChellappanRajan** [comment]
I am also facing same issue

**Comment by augustjk** [comment]
Yes, we should keep this issue open! It's still very much an issue affecting our users that we would like to address.

**Comment by tigrr** [comment]
Adding `"type": "module"` in `package.json` fixes the issue (you also have to rename `next.config.js` to `next.config.cjs`. However, if you run `npm run build` then `npm start` or `npm run dev`, open the page and look into the page source, you will see `<simple-greeter name="Friend"></simple-greeter>` in the output HTML and not the expected declarative shadow DOM.

**Comment by mohsenasfiamaersk** [comment]
Seems like using WSL in Windows fixes the issue

**Comment by siggerzz** [comment]
Also experiencing this issue :)

**Comment by flieks** [comment]
i also have the same problem

**Comment by orl0pl** [comment]
Still not fixed yet...
