### ISSUE TITLE
[labs/testing] Error when using a TemplateResult object inside expression

### ISSUE THREAD

**Issue by tigrr** [lit/lit#4015]
### Which package(s) are affected?

Other/unknown (please mention in description)

### Description

When I use a `TemplateResult` object returned by the `html` template function inside an expression like this:

```js
import { expect } from '@open-wc/testing'
import { html } from 'lit'
import { ssrFixture } from '@lit-labs/testing/fixtures.js'

const content = html`hello world`

describe('@lit-labs/testing', () => {
    it('should should accept template result as content', async () => {
		const el = await ssrFixture(
			html`<div>${content}</div>`,
			{
				modules: [],
				hydrate: true,
			},
		)

		expect(el.textContent).to.equal('hello world')
    })
})
```

I see the following error in the console:

```
Error: invalid template strings array
    at P (file:///C:/Users/user/Dev/test/web-test-runner/node_modules/lit-html/node/lit-html.js:6:858)
    at V (file:///C:/Users/user/Dev/test/web-test-runner/node_modules/lit-html/node/lit-html.js:6:1566)
    at getTemplateOpcodes (file:///C:/Users/user/Dev/test/web-test-runner/node_modules/@lit-labs/ssr/lib/render-value.js:120:31)
    at renderTemplateResult (file:///C:/Users/user/Dev/test/web-test-runner/node_modules/@lit-labs/ssr/lib/render-value.js:379:17)
    at renderTemplateResult.next (<anonymous>)
    at renderValue (file:///C:/Users/user/Dev/test/web-test-runner/node_modules/@lit-labs/ssr/lib/render-value.js:342:16)
    at renderValue.next (<anonymous>)
    at renderTemplateResult (file:///C:/Users/user/Dev/test/web-test-runner/node_modules/@lit-labs/ssr/lib/render-value.js:389:24)
    at renderTemplateResult.next (<anonymous>)
    at renderValue (file:///C:/Users/user/Dev/test/web-test-runner/node_modules/@lit-labs/ssr/lib/render-value.js:342:16)
src\ssr.test.js:

 ❌ @lit-labs/testing > should should accept template result as content
      Error: Error while executing command lit-ssr-render with payload {"template":{"_$litType$":1,"strings":["<div>","</div>"],"values":[{"_$litType$":1,"strings":["hello world"],"values":[]}]},"modules":[]}: invalid template strings array
        at async ssrFixture (node_modules\@lit-labs\testing\lib\fixtures\ssr-fixture.js:45:22)
        at async o.<anonymous> (src\ssr.test.js:9:14)
```

### Reproduction

1. `git clone https://github.com/tigrr/web-test-runner.git`
2. `git switch ssr`
3. `npm test`
4. Observe the error

### Workaround

I have not found a workaround

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

0.2.1

### Browser/OS/Node environment

OS: Windows 11
Node: 18.14.1
npm: 9.7.2

**Comment by m00k** [comment]
_'Dangerously spoofing TemplateStringsArray by adding back the `raw` property'_ to get past the [template results security check](https://github.com/lit/lit/blob/5beb5f9acbb5edb4f8df179d0e93fe4c9ae59b51/packages/lit-html/src/lit-html.ts#L666) should help you work around this limitation. Examples can be found in the lit source ([1](https://github.com/lit/lit/blob/5beb5f9acbb5edb4f8df179d0e93fe4c9ae59b51/packages/labs/testing/src/lib/worker.ts#L20))([2](https://github.com/lit/lit/blob/5beb5f9acbb5edb4f8df179d0e93fe4c9ae59b51/packages/lit-html/src/directives/unsafe-html.ts#L51))([3](https://github.com/lit/lit/blob/5beb5f9acbb5edb4f8df179d0e93fe4c9ae59b51/packages/lit-html/src/static.ts#L151)).

**Comment by m00k** [comment]
to spell it out, something along these lines should do the trick:
```ts
import { expect } from '@open-wc/testing'
import { TemplateResult, html } from 'lit'
import { ssrFixture } from '@lit-labs/testing/fixtures.js'

const content = html`hello world`

const withContent = (
    prefix: string,
    content: TemplateResult,
    postfix: string,
): TemplateResult => {
    const result = {
        ...content,
        strings: [
            `${prefix}${content.strings[0]}${postfix}`,
        ] as unknown as TemplateStringsArray,
    }
    ;(result.strings as any).raw = result.strings
    return result
}

describe('@lit-labs/testing', () => {
    it('should should accept template result as content', async () => {
        const el = await ssrFixture(withContent('<div>', content, '</div>'), {
            modules: [],
            hydrate: true,
        })

        expect(el.textContent).to.equal('hello world')
    })
})
```

**Comment by augustjk** [comment]
@m00k is correct that it's due to it failing the template result check. Though the fix is more of a hack that I wouldn't be comfortable endorsing.

Because the values need to to be serialized between the browser environment that the test runs in and the dev server doing the SSR, there is a limitation on the kinds of expression values this works with. This definitely should be documented better.

Answering whether this limitation is valid is tricky because this limitation is present for certain SSR limitations like using `@lit-labs/eleventy-plugin-lit` in worker mode, while it's fine for SSR-ing in the global space (which arguably might be the more common use case at the moment).

**Comment by augustjk** [comment]
Not automatically in a way that passed our check without adding back/spoofing the `raw` property of `TemplateStringsArray`.

We could add extra serialization logic in the test code running in the client to add some string marker for template results such that we can deserialize in the SSR worker.
