### ISSUE TITLE
SSR Declarative Shadow DOM in `html` literal with interpolations

### ISSUE THREAD

**Issue by dgp1130** [lit/lit#4058]
### Which package(s) are affected?

SSR (@lit-labs/ssr)

### Description

When attempting to render DSD via the SSR package and including an interpolation in the shadow DOM section, Lit throws an assertion error. A simplified version of what I'm trying to do:

```typescript
import {render} from '@lit-labs/ssr';

const name = 'World';
render(html`
  <div>
    <template shadowrootmode="open">
      <div>Hello, ${name}!</div>
      <style>div { color: green; }</style>
    </template>
  </div>
`);
```

This throws the following error when consuming the rendered template:

<details>
<summary>Error</summary>

```
Error: unexpected final partIndex: 0 !== 1
    at renderTemplateResult (file:///home/doug/.cache/bazel/_bazel_doug/0000b3b3fa770637f16a71f2a8299a7e/execroot/rules_prerender/bazel-out/k8-opt-exec-2B5CBBC6/bin/node_modules/.aspect_rules_js/@lit-labs+ssr@3.1.5/node_modules/@lit-labs/ssr/lib/render-value.js:508:15)
    at renderTemplateResult.next (<anonymous>)
    at renderValue (file:///home/doug/.cache/bazel/_bazel_doug/0000b3b3fa770637f16a71f2a8299a7e/execroot/rules_prerender/bazel-out/k8-opt-exec-2B5CBBC6/bin/node_modules/.aspect_rules_js/@lit-labs+ssr@3.1.5/node_modules/@lit-labs/ssr/lib/render-value.js:342:16)
    at renderValue.next (<anonymous>)
    at render (file:///home/doug/.cache/bazel/_bazel_doug/0000b3b3fa770637f16a71f2a8299a7e/execroot/rules_prerender/bazel-out/k8-opt-exec-2B5CBBC6/bin/node_modules/.aspect_rules_js/@lit-labs+ssr@3.1.5/node_modules/@lit-labs/ssr/lib/render.js:28:12)
    at render.next (<anonymous>)
    at collectResult (file:///home/doug/.cache/bazel/_bazel_doug/0000b3b3fa770637f16a71f2a8299a7e/execroot/rules_prerender/bazel-out/k8-opt-exec-2B5CBBC6/bin/node_modules/.aspect_rules_js/@rules_prerender+lit_engine@0.0.0/node_modules/@rules_prerender/lit_engine/index.mjs:25:16)
    at renderToHtml (file:///home/doug/.cache/bazel/_bazel_doug/0000b3b3fa770637f16a71f2a8299a7e/execroot/rules_prerender/bazel-out/k8-opt-exec-2B5CBBC6/bin/node_modules/.aspect_rules_js/@rules_prerender+lit_engine@0.0.0/node_modules/@rules_prerender/lit_engine/index.mjs:11:28)
```

</details>

I originally thought I was experiencing https://github.com/lit/lit/issues/2246, however I believe that has been fixed and I'm still seeing the same issue.

I'm not sure if static expressions are expected to be required when rendering DSD, however even using those I get the same error. I _think_ it should be ok for a DSD template to use dynamic expressions since it gets immediately turned into DOM nodes like any other DOM node, but I might not be fully understanding the security story. I'd be very interested to know if rendering DSD inherently requires all the expressions to be static.

### Reproduction

[Lit Playground reproduction](https://lit.dev/playground/#project=W3sibmFtZSI6InRlc3QtY2FzZXMudHMiLCJjb250ZW50IjoiLyoqXG4gKiBAZmlsZW92ZXJ2aWV3IFRlc3QgY2FzZXMgb2YgdXNpbmcgRFNEIGluIGEgYGh0bWxgIHRlbXBsYXRlLlxuICogQ2hyb21lLW9ubHkgYmVjYXVzZSB0aGlzIGhhcHBlbnMgdG8gcmVseSBvbiBhbiB1bnNwZWNjZWQgRFNEIGZlYXR1cmUuXG4gKi9cblxuaW1wb3J0IHsgaHRtbCB9IGZyb20gJ2xpdC1odG1sJztcbmltcG9ydCB7IGh0bWwgYXMgc3RhdGljSHRtbCwgdW5zYWZlU3RhdGljIH0gZnJvbSAnbGl0L3N0YXRpYy1odG1sLmpzJztcbmltcG9ydCB7IHJlbmRlclRvQm9keSB9IGZyb20gJy4vbGliLmpzJztcblxuY29uc3QgbmFtZSA9ICdXb3JsZCc7XG5cbi8vIFVzZXMgbm9ybWFsIGBodG1sYCB0ZW1wbGF0ZSBsaXRlcmFscy5cbmF3YWl0IHJlbmRlclRvQm9keSgnRHluYW1pYyAtIE5vIGludGVycG9sYXRpb25zJywgaHRtbGBcbiAgPGRpdj5cbiAgICA8dGVtcGxhdGUgc2hhZG93cm9vdG1vZGU9XCJvcGVuXCI-XG4gICAgICA8ZGl2PkhlbGxvLCBXb3JsZCE8L2Rpdj5cbiAgICAgIDxzdHlsZT5kaXYgeyBjb2xvcjogcmVkOyB9PC9zdHlsZT5cbiAgICA8L3RlbXBsYXRlPlxuICA8L2Rpdj5cbmApO1xuYXdhaXQgcmVuZGVyVG9Cb2R5KCdEeW5hbWljIC0gTGlnaHQgRE9NIGludGVycG9sYXRpb24nLCBodG1sYFxuICA8ZGl2PlxuICAgIDx0ZW1wbGF0ZSBzaGFkb3dyb290bW9kZT1cIm9wZW5cIj5cbiAgICAgIDxkaXY-SGVsbG8sIDxzbG90Pjwvc2xvdD4hPC9kaXY-XG4gICAgICA8c3R5bGU-ZGl2IHsgY29sb3I6IGJsdWU7IH08L3N0eWxlPlxuICAgIDwvdGVtcGxhdGU-XG4gICAgJHtuYW1lfVxuICA8L2Rpdj5cbmApO1xuYXdhaXQgcmVuZGVyVG9Cb2R5KCdEeW5hbWljIC0gU2hhZG93IERPTSBpbnRlcnBvbGF0aW9uJywgaHRtbGBcbiAgPGRpdj5cbiAgICA8dGVtcGxhdGUgc2hhZG93cm9vdG1vZGU9XCJvcGVuXCI-XG4gICAgICA8ZGl2PkhlbGxvLCAke25hbWV9ITwvZGl2PlxuICAgICAgPHN0eWxlPmRpdiB7IGNvbG9yOiBncmVlbjsgfTwvc3R5bGU-XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9kaXY-XG5gKTtcbmF3YWl0IHJlbmRlclRvQm9keSgnRHluYW1pYyAtIFNoYWRvdyBET00gc3RhdGljIGludGVycG9sYXRpb24nLCBodG1sYFxuICA8ZGl2PlxuICAgIDx0ZW1wbGF0ZSBzaGFkb3dyb290bW9kZT1cIm9wZW5cIj5cbiAgICAgIDxkaXY-SGVsbG8sICR7dW5zYWZlU3RhdGljKG5hbWUpfSE8L2Rpdj5cbiAgICAgIDxzdHlsZT5kaXYgeyBjb2xvcjogb3JhbmdlOyB9PC9zdHlsZT5cbiAgICA8L3RlbXBsYXRlPlxuICA8L2Rpdj5cbmApO1xuXG4vLyBVc2VzIGBodG1sYCBsaXRlcmFsIGZyb20gYHN0YXRpYy1odG1sLmpzYC5cbmF3YWl0IHJlbmRlclRvQm9keSgnU3RhdGljIC0gTm8gaW50ZXJwb2xhdGlvbnMnLCBzdGF0aWNIdG1sYFxuICA8ZGl2PlxuICAgIDx0ZW1wbGF0ZSBzaGFkb3dyb290bW9kZT1cIm9wZW5cIj5cbiAgICAgIDxkaXY-SGVsbG8sIFdvcmxkITwvZGl2PlxuICAgICAgPHN0eWxlPmRpdiB7IGNvbG9yOiByZWQ7IH08L3N0eWxlPlxuICAgIDwvdGVtcGxhdGU-XG4gIDwvZGl2PlxuYCk7XG5hd2FpdCByZW5kZXJUb0JvZHkoJ1N0YXRpYyAtIExpZ2h0IERPTSBpbnRlcnBvbGF0aW9uJywgc3RhdGljSHRtbGBcbiAgPGRpdj5cbiAgICA8dGVtcGxhdGUgc2hhZG93cm9vdG1vZGU9XCJvcGVuXCI-XG4gICAgICA8ZGl2PkhlbGxvLCA8c2xvdD48L3Nsb3Q-ITwvZGl2PlxuICAgICAgPHN0eWxlPmRpdiB7IGNvbG9yOiBibHVlOyB9PC9zdHlsZT5cbiAgICA8L3RlbXBsYXRlPlxuICAgICR7bmFtZX1cbiAgPC9kaXY-XG5gKTtcbmF3YWl0IHJlbmRlclRvQm9keSgnU3RhdGljIC0gU2hhZG93IERPTSBpbnRlcnBvbGF0aW9uJywgc3RhdGljSHRtbGBcbiAgPGRpdj5cbiAgICA8dGVtcGxhdGUgc2hhZG93cm9vdG1vZGU9XCJvcGVuXCI-XG4gICAgICA8ZGl2PkhlbGxvLCAke25hbWV9ITwvZGl2PlxuICAgICAgPHN0eWxlPmRpdiB7IGNvbG9yOiBncmVlbjsgfTwvc3R5bGU-XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9kaXY-XG5gKTtcbmF3YWl0IHJlbmRlclRvQm9keSgnU3RhdGljIC0gU2hhZG93IERPTSBzdGF0aWMgaW50ZXJwb2xhdGlvbicsIHN0YXRpY0h0bWxgXG4gIDxkaXY-XG4gICAgPHRlbXBsYXRlIHNoYWRvd3Jvb3Rtb2RlPVwib3BlblwiPlxuICAgICAgPGRpdj5IZWxsbywgJHt1bnNhZmVTdGF0aWMobmFtZSl9ITwvZGl2PlxuICAgICAgPHN0eWxlPmRpdiB7IGNvbG9yOiBvcmFuZ2U7IH08L3N0eWxlPlxuICAgIDwvdGVtcGxhdGU-XG4gIDwvZGl2PlxuYCk7XG4ifSx7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhRE9DVFlQRSBodG1sPlxuPGhlYWQ-XG4gIDxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiIHNyYz1cIi4vdGVzdC1jYXNlcy5qc1wiPjwvc2NyaXB0PlxuPC9oZWFkPlxuPGJvZHk-XG48L2JvZHk-XG4ifSx7Im5hbWUiOiJwYWNrYWdlLmpzb24iLCJjb250ZW50Ijoie1xuICBcImRlcGVuZGVuY2llc1wiOiB7XG4gICAgXCJsaXRcIjogXCJeMi4wLjBcIixcbiAgICBcIkBsaXQvcmVhY3RpdmUtZWxlbWVudFwiOiBcIl4xLjAuMFwiLFxuICAgIFwibGl0LWVsZW1lbnRcIjogXCJeMy4wLjBcIixcbiAgICBcImxpdC1odG1sXCI6IFwiXjIuMC4wXCJcbiAgfVxufSIsImhpZGRlbiI6dHJ1ZX0seyJuYW1lIjoibGliLnRzIiwiY29udGVudCI6ImltcG9ydCB7UmVuZGVyUmVzdWx0LCByZW5kZXJ9IGZyb20gJ0BsaXQtbGFicy9zc3InO1xuaW1wb3J0IHtUZW1wbGF0ZVJlc3VsdCwgaHRtbH0gZnJvbSAnbGl0JztcblxuLyoqXG4gKiBSZW5kZXIgdGhlIGdpdmVuIHRlbXBsYXRlIHJlc3VsdCBhbmQgYXBwZW5kIGl0IHRvIHRoZSBib2R5LCBsYWJlbGVkIGJ5IHRoZSBnaXZlbiBuYW1lLlxuICogVXNlcyBgQGxpdC1sYWJzL3NzcmAgdG8gcmVuZGVyLiBBcHBlbmRzIGFueSB0aHJvd24gZXJyb3IuXG4gKi9cbmV4cG9ydCBhc3luYyBmdW5jdGlvbiByZW5kZXJUb0JvZHkobmFtZTogc3RyaW5nLCBjb250ZW50OiBUZW1wbGF0ZVJlc3VsdCk6IFByb21pc2U8dm9pZD4ge1xuICBsZXQgcmVzdWx0OiBzdHJpbmc7XG4gIHRyeSB7XG4gICAgcmVzdWx0ID0gYXdhaXQgY29sbGVjdFJlc3VsdChyZW5kZXIoaHRtbGA8ZGl2PiR7bmFtZX0ke2NvbnRlbnR9PC9kaXY-YCkpO1xuICB9IGNhdGNoIChlcnIpIHtcbiAgICByZXN1bHQgPSBgPGRpdj4ke25hbWV9PGRpdj5FUlJPUjogJHtlcnIubWVzc2FnZX08L2Rpdj48L2Rpdj5gXG4gIH1cblxuICBkb2N1bWVudC5ib2R5LmFwcGVuZENoaWxkKHBhcnNlKHJlc3VsdCkpO1xufVxuXG4vKiogRm9ya2VkIGZyb20gaHR0cHM6Ly9naXRodWIuY29tL2xpdC9saXQvYmxvYi9jYWJjNjE4OTRlNTdiYTg5ZWNhZGMxZGViMjBmMTIxZmVjZGZmZmM5L3BhY2thZ2VzL2xhYnMvc3NyL3NyYy9saWIvcmVuZGVyLXJlc3VsdC50cyNMMjItTDMyICovXG5hc3luYyBmdW5jdGlvbiBjb2xsZWN0UmVzdWx0KHJlc3VsdDogUmVuZGVyUmVzdWx0KTogUHJvbWlzZTxzdHJpbmc-IHtcbiAgICBsZXQgdmFsdWUgPSAnJztcbiAgICBmb3IgKGNvbnN0IGNodW5rIG9mIHJlc3VsdCkge1xuICAgICAgICB2YWx1ZSArPSB0eXBlb2YgY2h1bmsgPT09ICdzdHJpbmcnXG4gICAgICAgICAgICA_IGNodW5rXG4gICAgICAgICAgICA6IGF3YWl0IGNvbGxlY3RSZXN1bHQoYXdhaXQgY2h1bmspO1xuICAgIH1cbiAgICByZXR1cm4gdmFsdWU7XG59XG5cbi8qIGBET01QYXJzZXIucHJvdG90eXBlLnBhcnNlRnJvbVN0cmluZ2Agc3VwcG9ydHMgRFNEIHZpYSBhbiB1bnNwZWNjZWQgQ2hyb21lLW9ubHkgZmVhdHVyZS4gKi9cbmNvbnN0IHBhcnNlRnJvbVN0cmluZyA9IERPTVBhcnNlci5wcm90b3R5cGUucGFyc2VGcm9tU3RyaW5nIGFzIChcbiAgdGhpczogRE9NUGFyc2VyLFxuICBjb250ZW50OiBzdHJpbmcsXG4gIG1pbWVUeXBlOiBzdHJpbmcsXG4gIC8vIFVuc3BlY2NlZCBDaHJvbWUtb25seSBmZWF0dXJlOiBodHRwczovL2RldmVsb3Blci5jaHJvbWUuY29tL2VuL2FydGljbGVzL2RlY2xhcmF0aXZlLXNoYWRvdy1kb20vI3BhcnNlci1vbmx5XG4gIG9wdGlvbnM6IHsgaW5jbHVkZVNoYWRvd1Jvb3RzOiBib29sZWFuIH0sXG4pID0-IERvY3VtZW50O1xuXG5mdW5jdGlvbiBwYXJzZShjb250ZW50OiBzdHJpbmcpOiBFbGVtZW50IHtcbiAgY29uc3QgZWwgPSBwYXJzZUZyb21TdHJpbmcuY2FsbChuZXcgRE9NUGFyc2VyKCksIGNvbnRlbnQsICd0ZXh0L2h0bWwnLCB7IGluY2x1ZGVTaGFkb3dSb290czogdHJ1ZSB9KTtcbiAgcmV0dXJuIGVsLmRvY3VtZW50RWxlbWVudDtcbn0ifV0)

Note this reproduction uses `includeShadowRoots` in `DOMParser` to apply SSR in a browser environment. As such it is a Chrome-only reproduction, however you can put a similar repro in a Node environment and get the same error.

### Workaround

I have not found a workaround.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

`lit-html` - 2.7.5, `@lit-labs/ssr` - 3.1.5 (current latest for both)

### Browser/OS/Node environment

Reproduces in both:
* Chrome 115
* Node: 18.12.1

**Comment by justinfagnani** [comment]
Lit 2.0 doesn't support bindings in `<template>`s, even in client code. We found this was a very rare use case that had a non-negligible cost on all templates to support. It also has unintuitive semantics to some: updating values in the template bindings does not update update any instances stamped from that template, only the template itself. That's better with declarative shadow DOM, but it was a consideration with removing this feature before DSD existed.

The way to do this now is to use a static template.

**Comment by dgp1130** [comment]
Static templates have the same error. Or are you saying that once this bug is fixed the recommendation will be to use static templates?

Would that mean that you have to use `literal` or `unsafeStatic` for every interpolation, or could I use dynamic expressions just as long as they use the static `html` import? I'm wondering how limiting this constraint would be for SSR'd DSD use cases.

The workaround I can think of is to put the interpolations in light DOM with `<slot name="...">` to put them in the right place, though that would leak the content and allow it to be overriddable by the component's parents, which might not be desired. Also it just has a really awkward DX.

**Comment by rictic** [comment]
We should be able to support this with our upcoming server-only templates feature. I'll take this on.
