### ISSUE TITLE
Property will not trigger updates as expected because it is set using class fields

### ISSUE THREAD

**Issue by andyjessop** [lit/lit#4411]
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

I'm defining a property like this:

```ts
import { css, html, LitElement } from 'lit';
import { customElement, property } from 'lit/decorators.js';

@customElement('rune-block-actions')
export class RuneBlockActions extends LitElement {
  @property()
  blockId: string;
```

I get the following console error:
```
reactive-element.ts:1392 Uncaught (in promise) Error: The following properties on element rune-block-actions will not trigger updates as expected because they are set using class fields: blockId. Native class fields and some compiled output will overwrite accessors used for detecting changes. See https://lit.dev/msg/class-field-shadowing for more information.
    at RuneBlockActions.performUpdate (reactive-element.ts:1392:17)
    at RuneBlockActions.scheduleUpdate (reactive-element.ts:1344:25)
    at RuneBlockActions.__enqueueUpdate (reactive-element.ts:1316:25)
```

I also get this TS error in the editor:
```
Property 'blockId' has no initializer and is not definitely assigned in the constructor.
```

### Reproduction

The code is unfortunately closed-source, and I cannot reproduce on the playground.

### Workaround

I have not found a workaround.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

3.0.2

### Browser/OS/Node environment

Browser: Chrome 119.0.6045.105
OS: Mac 14
Node: 18.6.1
npm: 9.5.1

**Comment by andyjessop** [comment]
Some extra info. I have this in the tsconfig:

```json
    "experimentalDecorators": true,
    "useDefineForClassFields": false,
    ```
And it's the same whether or not I add the options in the `property({ type: String })` decorator.

**Comment by AndrewJakubowicz** [comment]
The error "Property '...' has no initializer and is not definitely assigned in the constructor." is raised if you haven't initialized a property.

For example the following code:

```ts
class ExampleClass {
    name: string
//  ~~~~ Property 'name' has no initializer and is not definitely assigned in the constructor.
}
```

[Repro in TypeScript playground](https://www.typescriptlang.org/play?#code/MYGwhgzhAECiAeYC2AHEBTaBvAUNaAdsugFzQQAuATgJYEDmA3DgL447AD2Bl0mAvIXQB3OIlQYAFAEpmXHpwwA6EJ3qT0SoknSzoAen3QAMmpgBXAgBN0AMzrorQA)

This can be fixed in a couple ways. The simplest way is to initialize `blockId` to an initial value. In your example maybe an empty string?

```ts
@customElement('rune-block-actions')
export class RuneBlockActions extends LitElement {
  @property()
  blockId = "";
```

If for some reason you have a reason to not initialize the property, you can opt-out of setting an initial value with `!` ([TypeScript playground sample](https://www.typescriptlang.org/play?#code/MYGwhgzhAECiAeYC2AHEBTaBvAUNaA9AdAAoBO6AZumdAJYB2dALnWCHQF6MDm0KZAPYoardBAA09BhGbowAE2iDK0AK4Re0AAYBCbXmgNk6XQC5ossrwDcOAL44cwQTObRMAXiPoA7nERUDAAKAEo7FxlBDAA6EEEeYPQY4yR0cMJiABkEmDUGBSpGdAUgA)).

```ts
class ExampleClass {
    // Don't do this unless you know what you are doing.
    // TypeScript now types `name` to be a string, but it'll be `undefined` if no one initializes it.
    name!: string
}
```

**Comment by andyjessop** [comment]
The problem here is that the examples in the lit docs don't do any of what you described above. You need to set `"strictPropertyInitialization": false` in your `tsconfig.json`, and I don't see any mention of this in the docs. There is [this section](https://lit.dev/docs/components/properties/#avoiding-issues-with-class-fields), but the recommended `tsconfig` properties are not sufficient to suppress the warnings. Here are some of the examples from the docs:

```ts
class MyElement extends LitElement {
  @property()
  name: string;
}
``` 

```ts
class MyElement extends LitElement {
  @property({type: String})
  mode: string;
```

I would say that the takeaway here is that there needs to be a prominent section on `tsconfig`, probably both in [getting started](https://lit.dev/docs/getting-started/), and in the properties section, and it should recommend:

```json
"experimentalDecorators": true,
"useDefineForClassFields": false,
"strictPropertyInitialization": false
```

**Comment by AndrewJakubowicz** [comment]
You raise a great point about our documentation. We definitely need to address that. Thank you for calling it out. The examples you've pulled from the documentation should be changed to:

```ts
class MyElement extends LitElement {
  @property()
  name?: string;
}
```

and 

```ts
class MyElement extends LitElement {
  @property({type: String})
  mode?: string;
```

I wouldn't recommend globally changing `"strictPropertyInitialization": false` as that hinders the benefits of TypeScript, as the uninitialized property could be undefined. I'd lean towards either asserting with `!` that you know it must exist, or use `?` to declare that it may be `undefined` if uninitialized.

What do you think about those proposed changes?

**Comment by andyjessop** [comment]
I think that makes sense. Thanks very much for the clarification!
