### ISSUE TITLE
[Lit SSR]: fails with expressions inside of `<style>` tag

### ISSUE THREAD

**Issue by KonnorRogers** [lit/lit#4696]
### Which package(s) are affected?

SSR (@lit-labs/ssr)

### Description

When using a dynamic variable inside of a `render()` function with a `<style>` tag, Lit SSR produces the following error:

<details>
<summary>Error Log</summary>

```
Error: 
      Unexpected final partIndex: 1 !== 2 while processing the following template:
  
      
        ${...}
  
        <!-- Errors -->
        <style>
        .block {
          display: flex;
          align-items: center;
          justify-content: center;
          height: 100px;
          background-color: ${...};
        }
        </style>
  
        <div class="block">
          <slot></slot>
        </div>
      
  
      This could be because you're attempting to render an expression in an invalid location. See
      https://lit.dev/docs/templates/expressions/#invalid-locations for more information about invalid expression
      locations.
    
      at throwErrorForPartIndexMismatch (file:///project/workspace/node_modules/@lit-labs/ssr/lib/render-value.js:610:11)
      at renderTemplateResult (file:///project/workspace/node_modules/@lit-labs/ssr/lib/render-value.js:597:9)
      at renderTemplateResult.next (<anonymous>)
      at renderValue (file:///project/workspace/node_modules/@lit-labs/ssr/lib/render-value.js:409:16)
      at renderValue.next (<anonymous>)
      at LitElementRenderer.renderShadow (file:///project/workspace/node_modules/@lit-labs/ssr/lib/lit-element-renderer.js:69:16)
      at renderShadow.next (<anonymous>)
      at renderTemplateResult (file:///project/workspace/node_modules/@lit-labs/ssr/lib/render-value.js:583:21)
      at renderTemplateResult.next (<anonymous>)
      at renderValue (file:///project/workspace/node_modules/@lit-labs/ssr/lib/render-value.js:409:16)

  xxx GET / 500 23ms -

  Error: 
      Unexpected final partIndex: 1 !== 2 while processing the following template:
  
      
        ${...}
  
        <!-- Errors -->
        <style>
        .block {
          display: flex;
          align-items: center;
          justify-content: center;
          height: 100px;
          background-color: ${...};
        }
        </style>
  
        <div class="block">
          <slot></slot>
        </div>
      
  
      This could be because you're attempting to render an expression in an invalid location. See
      https://lit.dev/docs/templates/expressions/#invalid-locations for more information about invalid expression
      locations.
    
      at throwErrorForPartIndexMismatch (file:///project/workspace/node_modules/@lit-labs/ssr/lib/render-value.js:610:11)
      at renderTemplateResult (file:///project/workspace/node_modules/@lit-labs/ssr/lib/render-value.js:597:9)
      at renderTemplateResult.next (<anonymous>)
      at renderValue (file:///project/workspace/node_modules/@lit-labs/ssr/lib/render-value.js:409:16)
      at renderValue.next (<anonymous>)
      at LitElementRenderer.renderShadow (file:///project/workspace/node_modules/@lit-labs/ssr/lib/lit-element-renderer.js:69:16)
      at renderShadow.next (<anonymous>)
      at renderTemplateResult (file:///project/workspace/node_modules/@lit-labs/ssr/lib/render-value.js:583:21)
      at renderTemplateResult.next (<anonymous>)
      at renderValue (file:///project/workspace/node_modules/@lit-labs/ssr/lib/render-value.js:409:16)

  <-- GET /

  Error: 
      Unexpected final partIndex: 1 !== 2 while processing the following template:
  
      
        ${...}
  
        <!-- Errors -->
        <style>
        .block {
          display: flex;
          align-items: center;
          justify-content: center;
          height: 100px;
          background-color: ${...};
        }
        </style>
  
        <div class="block">
          <slot></slot>
        </div>
      
  
      This could be because you're attempting to render an expression in an invalid location. See
      https://lit.dev/docs/templates/expressions/#invalid-locations for more information about invalid expression
      locations.
    
      at throwErrorForPartIndexMismatch (file:///project/workspace/node_modules/@lit-labs/ssr/lib/render-value.js:610:11)
      at renderTemplateResult (file:///project/workspace/node_modules/@lit-labs/ssr/lib/render-value.js:597:9)
      at renderTemplateResult.next (<anonymous>)
      at renderValue (file:///project/workspace/node_modules/@lit-labs/ssr/lib/render-value.js:409:16)
      at renderValue.next (<anonymous>)
      at LitElementRenderer.renderShadow (file:///project/workspace/node_modules/@lit-labs/ssr/lib/lit-element-renderer.js:69:16)
      at renderShadow.next (<anonymous>)
      at renderTemplateResult (file:///project/workspace/node_modules/@lit-labs/ssr/lib/render-value.js:583:21)
      at renderTemplateResult.next (<anonymous>)
      at renderValue (file:///project/workspace/node_modules/@lit-labs/ssr/lib/render-value.js:409:16)

  xxx GET / 500 4ms -

  Error: 
      Unexpected final partIndex: 1 !== 2 while processing the following template:
  
      
        ${...}
  
        <!-- Errors -->
        <style>
        .block {
          display: flex;
          align-items: center;
          justify-content: center;
          height: 100px;
          background-color: ${...};
        }
        </style>
  
        <div class="block">
          <slot></slot>
        </div>
      
  
      This could be because you're attempting to render an expression in an invalid location. See
      https://lit.dev/docs/templates/expressions/#invalid-locations for more information about invalid expression
      locations.
    
      at throwErrorForPartIndexMismatch (file:///project/workspace/node_modules/@lit-labs/ssr/lib/render-value.js:610:11)
      at renderTemplateResult (file:///project/workspace/node_modules/@lit-labs/ssr/lib/render-value.js:597:9)
      at renderTemplateResult.next (<anonymous>)
      at renderValue (file:///project/workspace/node_modules/@lit-labs/ssr/lib/render-value.js:409:16)
      at renderValue.next (<anonymous>)
      at LitElementRenderer.renderShadow (file:///project/workspace/node_modules/@lit-labs/ssr/lib/lit-element-renderer.js:69:16)
      at renderShadow.next (<anonymous>)
      at renderTemplateResult (file:///project/workspace/node_modules/@lit-labs/ssr/lib/render-value.js:583:21)
      at renderTemplateResult.next (<anonymous>)
      at renderValue (file:///project/workspace/node_modules/@lit-labs/ssr/lib/render-value.js:409:16)

```

</details>

### Reproduction

https://codesandbox.io/p/devbox/goofy-shirley-jgslml?file=%2Fcomponents%2Fcustom-block.js%3A34%2C8

### Workaround

The only workaround I have found is to use `unsafeHTML` directive.

`staticHTML` also does not solve the issue either.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

Failing in 3.2.2 of Lit SSR

### Browser/OS/Node environment

Browser: N/A
Node: v20.12.1
Lit SSR: 3.2.2
Lit: 3.1.4

**Comment by justinfagnani** [comment]
I have a fix for this

**Comment by justinfagnani** [comment]
> I have a fix for this.

Or not. Raw text element handling in SSR is tricky. I can easily make a better error message that recommends `unsafeHTML()`.

**Comment by justinfagnani** [comment]
I think we can support raw text elements with this strategy:

- Don't emit `<!--lit-part-->` markers inside raw text elements
- Add a way to describe child parts in `<!--lit-node-->` by text offset, maybe like `<!--lit-part 0 5,10;21,31-->` where `5,10;21,31` says that there's a child part from chars 5-10 and 21-31. This requires that `textContent` isn't modified by the browser (to confirm).

**Comment by KevinEdry** [comment]
Any progress on this? I have the same issue with a script tag.
```ts
what I want to inject for example:
 const content = `console.log('Hello from script tag');`

  <script>
    ${content}
  </script>
```

And I am getting the same error.

**Comment by KonnorRogers** [comment]
> Any progress on this? I have the same issue with a script tag.
> 
> what I want to inject for example:
>  const content = `console.log('Hello from script tag');`
> 
>   <script>
>     ${content}
>   </script>
> 
> And I am getting the same error.

The way I'm solving this for now is wrapping the `<script>` in an `unsafeHTML()` like this:

```js
      <!-- unsafeHTML needed for SSR until this is solved: https://github.com/lit/lit/issues/4696 -->
      ${unsafeHTML(`
        <style id="mobile-styles">
          ${mobileStyles(this.mobileBreakpoint)}
        </style>
      `)}

```
