### ISSUE TITLE
Styles imported from external stylesheets aren't working.

### ISSUE THREAD

**Issue by swyrik** [lit/lit#4811]
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

We are importing stylesheets from outside. getting the below error in the browser. I don't want to override _createRenderRoot_. I want to go with shadowdom and external style sheets. please help

```
css-tag.js:6  Uncaught TypeError: Failed to set the 'adoptedStyleSheets' property on 'ShadowRoot': Failed to convert value to 'CSSStyleSheet'.
    at css-tag.js:6:1001
    at s.createRenderRoot (reactive-element.js:6:3073)
    at s.createRenderRoot (lit-element.js:6:137)
    at s.connectedCallback (reactive-element.js:6:3154)
    at s.connectedCallback (lit-element.js:6:403)
```

This is my lit-element.

```
import {LitElement, html } from  'lit-element';
import {customElement} from 'lit/decorators.js';
import styles from './buttons-styles.css';

@customElement('add-button')
export class AddButton extends LitElement{

    static override styles = [styles];

```

### Reproduction

I'm unbale to reproduce this in lit playground it isn't allowing me to import external css styles at all.

### Workaround

I have not found a workaround.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

3.2.0

### Browser/OS/Node environment

Browser: Edge130.0.2849.46 
OS: Windows 10
Node: v16.20.2
npm: 8.19.4

**Comment by augustjk** [comment]
What are you using for your build system? The following syntax is not a valid platform way to import css.
```js
import styles from './buttons-styles.css';
```

The platform native way is to use [import attributes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import/with#:~:text=HTML%20spec%20also%20defines%20the%20css%20type%2C%20which%20imports%20a%20CSSStyleSheet%20object) which will import as a `CSSStyleSheet` usable by Lit directly.
```js
import styles from './buttons-styles.css' with { type: 'css'};
```

If you're using something like Vite, it does its own thing for the import so you need to import the raw string with [`?inline`](https://vite.dev/guide/features.html#disabling-css-injection-into-the-page) and pass it into `unsafeCSS()`
```js
import {LitElement, html, unsafeCSS } from  'lit-element';
import {customElement} from 'lit/decorators.js';
import styles from './buttons-styles.css?inline';

@customElement('add-button')
export class AddButton extends LitElement{

    static override styles = [unsafeCSS(styles)];

```

**Comment by swyrik** [comment]
Tried the suggestions you have mentioned @augustjk. It's still not working. Here is the repo for my code.

https://github.com/swyrik/lit-component

_**npm run docs**_ to build it.

**Comment by augustjk** [comment]
I'm not sure what the status of rollup importing styles with or without import attributes is currently like. Import attributes are still experimental and lacking support in some tools.
An easy way around this is to write your css inside `css` tag function and export it from a TS file as described in https://lit.dev/docs/components/styles/#sharing-styles
If you're using some other css pre/post processor, this won't be seamless.

**Comment by justinfagnani** [comment]
I think this is a tooling issue rather than a Lit issue. Many tools and browsers don't support standard CSS imports yet. Lit supports adding plain CSSStyleSheets to the styles array, and that's covered by tests.
